// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';

export function ClipboardCopy(arg1:string,arg2:number):Promise<void>;

export function GetContext():Promise<context.Context>;

export function PasswordGenerate(arg1:models.GeneratorOptions):Promise<string>;

export function RecordCreate(arg1:models.RecordInput):Promise<string>;

export function RecordDelete(arg1:string):Promise<void>;

export function RecordGet(arg1:string):Promise<models.RecordDetail>;

export function RecordHistory(arg1:string):Promise<Array<models.SecretHistory>>;

export function RecordList(arg1:string):Promise<Array<models.RecordSummary>>;

export function RecordListTrash():Promise<Array<models.RecordSummary>>;

export function RecordPurge(arg1:string):Promise<void>;

export function RecordRestore(arg1:string):Promise<void>;

export function RecordUpdate(arg1:string,arg2:models.RecordInput):Promise<void>;

export function VaultCreate(arg1:string):Promise<void>;

export function VaultExists():Promise<boolean>;

export function VaultIsUnlocked():Promise<boolean>;

export function VaultLock():Promise<void>;

export function VaultUnlock(arg1:string):Promise<void>;
