// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardCopy(arg1, arg2) {
  return window['go']['backend']['App']['ClipboardCopy'](arg1, arg2);
}

export function GetContext() {
  return window['go']['backend']['App']['GetContext']();
}

export function PasswordGenerate(arg1) {
  return window['go']['backend']['App']['PasswordGenerate'](arg1);
}

export function RecordCreate(arg1) {
  return window['go']['backend']['App']['RecordCreate'](arg1);
}

export function RecordDelete(arg1) {
  return window['go']['backend']['App']['RecordDelete'](arg1);
}

export function RecordGet(arg1) {
  return window['go']['backend']['App']['RecordGet'](arg1);
}

export function RecordHistory(arg1) {
  return window['go']['backend']['App']['RecordHistory'](arg1);
}

export function RecordList(arg1) {
  return window['go']['backend']['App']['RecordList'](arg1);
}

export function RecordListTrash() {
  return window['go']['backend']['App']['RecordListTrash']();
}

export function RecordPurge(arg1) {
  return window['go']['backend']['App']['RecordPurge'](arg1);
}

export function RecordRestore(arg1) {
  return window['go']['backend']['App']['RecordRestore'](arg1);
}

export function RecordUpdate(arg1, arg2) {
  return window['go']['backend']['App']['RecordUpdate'](arg1, arg2);
}

export function VaultCreate(arg1) {
  return window['go']['backend']['App']['VaultCreate'](arg1);
}

export function VaultExists() {
  return window['go']['backend']['App']['VaultExists']();
}

export function VaultIsUnlocked() {
  return window['go']['backend']['App']['VaultIsUnlocked']();
}

export function VaultLock() {
  return window['go']['backend']['App']['VaultLock']();
}

export function VaultUnlock(arg1) {
  return window['go']['backend']['App']['VaultUnlock'](arg1);
}
